Project/sources/ETOS/ETOS.WebUI/ViewModels/RequestsViewModels.cs
using ETOS.Core.DTO;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ETOS.WebUI.ViewModels
{
	/// <summary>
	/// ViewModel-и для страницы с заявками
	/// </summary>
	public class RequestsViewModels
	{

		/// <summary>
		/// ViewModel для окна изменение заявки
		/// </summary>
		public class EditRequestModel
		{
			public DtoRequest Request { get; set; }
			public SelectList POIList { get; set; }
			public SelectList StatusesList { get; set; }
			public List<string> Errors { get; set; }
		}

		/// <summary>
		/// ViewModel для окна создание заявки
		/// </summary>
		public class CreateRequestModel
		{
			public DtoCreateRequest Request { get; set; }
			public SelectList POIList { get; set; }
			public SelectList POIListAddresses { get; set; }
			public List<string> Errors { get; set; }
		}


        public class RequestIndexViewModel
        {
            public PagedList.IPagedList<ETOS.Core.DTO.DtoRequest> Requests;
        }

        public class RequestHandleViewModel
        {
            public DtoRequest Request { get; set; }
            public string Error { get; set; }
        }

        public class RequestRejectViewModel
        {
            public string Comment { get; set; }
            public int Id { get; set; }
            public string Error { get; set; }
        }
    }
}

Project/sources/ETOS/ETOS.WebUI/Controllers/ContractorController.cs
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;

using ETOS.Core.DTO;
using ETOS.Core.Services.Abstract;
using ETOS.WebUI.ViewModels;
using ETOS.WebUI.RequestPriceCalculator;

namespace ETOS.WebUI.Controllers
{
	/// <summary>
	/// Контроллер, обеспечивающий работу с подрядчиками на уровне представления.
	/// </summary>
	[Authorize]
    public class ContractorController : Controller
    {
        #region Fields

        IRequestService _requestService;
        ILocationService _locationService;
        IContractorService _contractorService;

        #endregion 

        #region Constructor

        public ContractorController(IRequestService reqService, ILocationService locService, IContractorService contractorService)
        {
            _requestService = reqService;
            _locationService = locService;
            _contractorService = contractorService;
        }

        #endregion 

        #region Methods

        /// <summary>
        /// Get-версия метода, возвращающая представление с подрядчиками подходящими данной заявке
        /// </summary>        
        [HttpGet]
        public ViewResult Select(int id)
        {
            var model = new ContractorViewModel();
            model.errors = new List<string>();
            var error = "";
            var request = new DtoRequest();
            if (!_requestService.GetRequestById(id, out request, out error))
            {
                model.errors.Add(error);
            }

            model.RequestId = request.Id;
            model.Mileage = request.Mileage;

            int? DeparturePointId = null;
         
            if (request.DeparturePointId != null)
            {
                DeparturePointId = request.DeparturePointId;
                model.DepartureAddress = _locationService.GetPOIById((int)DeparturePointId).Name;
            }
            else
            {
                model.DepartureAddress = request.DepartureAddress;
            }


			int? DestinationPointId = null;

			if (request.DestinationPointId != null)
			{
				DestinationPointId = request.DestinationPointId;
				model.DestinationAddress = _locationService.GetPOIById((int)DestinationPointId).Name;
			}
			else
			{
				model.DestinationAddress = request.DestinationAddress;
			}


			model.contractors = _contractorService.GetAllContractors();

            if (model.contractors == null || model.contractors.Count == 0)
            {
                model.errors.Add("Не найдено подходящих вариантов для данной поездки");
            }

			var requestPriceCalculator = new RequestPriceCalculatingServiceClient();
            
			// заполняем цену поездки для каждого подрядчика 
            foreach (var contractor in model.contractors)
            {
				contractor.TotalPrice = /*(decimal)model.Mileage * contractor.Tariff;*/ requestPriceCalculator.CalculateRequestPrice(model.Mileage, contractor.Tariff);
			}

			requestPriceCalculator.Close();

            return View(model);
        }

        /// <summary>
        /// Get-версия метода, возвращающая представление для создания новой заявки.
        /// </summary>
        [HttpPost]
        public ActionResult Select(ContractorViewModel model)
        {
            var error = "";
            if (model.errors == null) model.errors = new List<string>();

            if (!_contractorService.SetContractorForRequest(out error, model.SelectedContractorId, model.RequestId, model.Comment))
            {
                model.errors.Add(error);
                return View(model);
            }
            return RedirectToAction("Index", "Request");
        }

		public ViewResult Index()
		{
			var model = new ContractorListViewModel
			{
				Contractors = _contractorService.GetContractorsList()
					.Select(c => new ContractorInfoViewModel
					{
						Id = c.Id,
						Name = c.Name,
						Phone = c.Phone,
						Tariff = c.Tariff
					})
			};

			return View(model);
		}

		public ViewResult Create()
		{
			ViewBag.Title = "Добавление нового подрядчика";

			return View("Edit", new ContractorInfoViewModel { Id = 0 });
		}

		public ViewResult Edit(int contractorId)
		{
			var contractorDto = _contractorService.GetContractor(contractorId);

			if (contractorDto != null)
			{
				var model = new ContractorInfoViewModel
				{
					Id = contractorDto.Id,
					Name = contractorDto.Name,
					Phone = contractorDto.Phone,
					Tariff = contractorDto.Tariff
				};

				ViewBag.Title = "Редактирование данных подрядчика";

				return View(model);
			}

			return View("_Error");
		}

		public ActionResult Save(ContractorInfoViewModel model)
		{
			if (ModelState.IsValid)
			{
				var contractor = new DtoContractor
				{
					Id = model.Id,
					Name = model.Name,
					Phone = model.Phone,
					Tariff = model.Tariff
				};

				_contractorService.SaveContractor(contractor);

				return RedirectToAction("Index");
			}
			else
			{
				if (model.Id > 0)
				{
					return RedirectToAction("Edit", new { contractorId = model.Id });
				}
				else
				{
					return RedirectToAction("Create");
				}
			}
		}
		
		public ActionResult Remove(int contractorId)
		{
			if (contractorId > 0)
			{
				_contractorService.RemoveContractor(contractorId);

				return RedirectToAction("Index");
			}
			else
			{
				return View("_Error");
			}
		}
		
		#endregion
	}
}

Project/sources/ETOS/ETOS.WebUI/Controllers/RequestController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web;

using ETOS.Core.DTO;
using ETOS.Core.Services.Abstract;
using ETOS.Common;
using static ETOS.WebUI.ViewModels.RequestsViewModels;

using PagedList;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using ETOS.WebUI.ViewModels;
using ETOS.DAL.Enums;
using System;
using ETOS.WSL;

namespace ETOS.WebUI.Controllers
{
	/// <summary>
	/// Контроллер, обеспечивающий работу с заявками на уровне представления.
	/// </summary>
	[Authorize]
	public class RequestController : Controller
	{
		#region Fields

		IRequestService _requestService;
		ILocationService _locationService;
		private DisplayFilter _displayFilter;
		private LogFilter _logFilter;
		IEmployeeService _employeeService;
		ILogService _logService;

		private IApplicationUserService _userService
		{
			get
			{
				return HttpContext.GetOwinContext().GetUserManager<IApplicationUserService>();
			}
		}
		#endregion

		#region Constructor

		public RequestController(IRequestService reqService, ILocationService locService, IEmployeeService employeeService, ILogService logService)
		{
			_requestService = reqService;
			_locationService = locService;
			_employeeService = employeeService;
			_logService = logService;
		}

		#endregion

		#region Methods

		[HttpGet]
		public ActionResult Index()
		{
			if (HttpContext.User.IsInRole("Секретарь"))
			{
				return RedirectToAction("PartialSecretaryIndex", "Request");
			}
			if (HttpContext.User.IsInRole("Бухгалтер"))
			{
				return RedirectToAction("Index", "Request");
			}
			if (HttpContext.User.IsInRole("Менеджер"))
			{
				return RedirectToAction("PartialManagerIndex", "Request");
			}
			if (HttpContext.User.IsInRole("Администратор"))
			{
				return RedirectToAction("PartialAdminIndex", "Request");
			}
			return RedirectToAction("PartialRequestIndex", "Request");
		}

		/// <summary>
		/// Get-версия метода, возвращающая представление с полным перечнем заявок.
		/// </summary>
		[HttpGet]
		public ActionResult PartialRequestIndex(DisplayFilter displayFilter, string cleanFilter, int? page)
		{

			if (displayFilter.AuthorFirstName != null || displayFilter.AuthorLastName != null || displayFilter.DepartureAddress != null || displayFilter.DestinationAddress != null)
			{
				Session["disFilter"] = displayFilter;
				_displayFilter = displayFilter;
			}
			else
			{
				if (_displayFilter == null && (DisplayFilter)Session["disFilter"] == null)
				{
					_displayFilter = (new DisplayFilter()).GetDefault();
				}
				else
				{
					_displayFilter = (DisplayFilter)Session["disFilter"];
				}
			}
			if (cleanFilter == "true")
			{
				_displayFilter = (new DisplayFilter()).GetDefault();
			}

			if (displayFilter.AuthorFirstName == null && displayFilter.AuthorLastName == null && displayFilter.DepartureAddress == null && displayFilter.DestinationAddress == null)
			{
				_displayFilter = (new DisplayFilter()).GetDefault();
			}

			var userId = _userService.GetUserByMail(HttpContext.User.Identity.Name).Id;
			var userName = _employeeService.GetUserLastName(userId).Lastname;
			_displayFilter.AuthorLastName = userName;

			int pageSize = 5;
			int pageNumber = (page ?? 1);

			var model = new RequestIndexViewModel();

			var requestsList = _requestService.GetRequest(_displayFilter).OrderByDescending(x => x.Id);
			model.Requests = requestsList.ToPagedList(pageNumber, pageSize);

			return PartialView(model);
		}

		[HttpGet]
		public ViewResult MoreDetails(int Id)
		{
			string error = "";

			var request = new DtoRequest();

			_requestService.GetRequestById(Id, out request, out error);

			var model = new EditRequestModel();

			model.Request = request;

			return View(model);
		}

		/// <summary>
		/// Get-версия метода, возвращающая представление с полями заявки
		/// </summary>
		[HttpGet]
		public ActionResult Edit()
		{
			return View();
		}

		/// <summary>
		/// Post - Версия метода обновляет заявку или выводит ошибки
		/// </summary>
		[HttpPost]
		public ActionResult Edit(RequestsViewModels model)
		{
			return View(model);

		}

		/// <summary>
		/// Get-версия метода, возвращающая представление для создания новой заявки.
		/// </summary>
		[HttpGet]
		public ViewResult Create()
		{
			var model = new CreateRequestModel();

			var poiList = _locationService.GetPOIList();

			model.POIList = new SelectList(poiList, "Id", "Name");
			model.POIListAddresses = new SelectList(poiList, "Id", "Address");

			model.Request = new DtoCreateRequest();

			return View(model);
		}

		/// <summary>
		/// Get-версия метода, возвращающая представление для создания новой заявки.
		/// </summary>
		[HttpPost]
		public ActionResult Create(CreateRequestModel model)
		{

			var valid = true;
			var addresses = new List<string>();

			if (model.Errors == null) model.Errors = new List<string>();

			if (model.Request.DepartureAddress == "" && model.Request.DeparturePointId == 0)
			{
				model.Errors.Add("Укажите адрес отправления");
				valid = false;
			}

			if (model.Request.DestinationAddress == "" && model.Request.DestinationPointId == 0)
			{
				model.Errors.Add("Укажите адрес назначения");
				valid = false;
			}

			//TODO сделать валидацию даты времени отправления

			if (!valid)
			{
				var poiList = _locationService.GetPOIList();
				model.POIList = new SelectList(poiList, "Id", "Name");
				model.POIListAddresses = new SelectList(poiList, "Id", "Address");

				return View(model);
			}

			var mileageService = new MileageCalculatingService();
			string calcDestinationAddress;
			string calcDepartureAddress;

			if (model.Request.DestinationPointId == 0)
			{
				calcDestinationAddress = model.Request.DestinationAddress;
			}
			else
			{
				calcDestinationAddress = _locationService.GetPOIById(model.Request.DestinationPointId).Address;
			}

			if (model.Request.DeparturePointId == 0)
			{
				calcDepartureAddress = model.Request.DepartureAddress;
			}
			else
			{
				calcDepartureAddress = _locationService.GetPOIById(model.Request.DeparturePointId).Address;
			}

			model.Request.Mileage = mileageService.GetMileage(calcDepartureAddress, calcDestinationAddress);


			model.Request.AuthorLogin = User.Identity.Name;
			var error = "";
			if (!_requestService.AddRequest(model.Request, out error))
			{
				model.Errors.Add(error);
				var poiList = _locationService.GetPOIList();
				model.POIList = new SelectList(poiList, "Id", "Name");
				model.POIListAddresses = new SelectList(poiList, "Id", "Address");
				return View(model);
			}

			var userId = _userService.GetUserByMail(HttpContext.User.Identity.Name).Id;

			var newLog = new DtoLog()
			{
				CreatorFirstName = _employeeService.GetUserLastName(userId).Firstname,
				CreatorLastName = _employeeService.GetUserLastName(userId).Lastname,
				BrowserName = HttpContext.Request.Browser.Browser,
				IpAddress = HttpContext.Request.UserHostAddress,
				RequestMile = model.Request.Mileage,
				RequestPrice = 10
			};

			_logService.AddLog(newLog, out error);

			return RedirectToAction("Index", "Request");
		}
		[Authorize(Roles = "Секретарь")]
		[HttpGet]
		public ActionResult PartialSecretaryIndex(DisplayFilter displayFilter, string cleanFilter, int? page)
		{

			if (displayFilter.AuthorFirstName != null || displayFilter.AuthorLastName != null || displayFilter.DepartureAddress != null || displayFilter.DestinationAddress != null)
			{
				_displayFilter = displayFilter;
			}
			else
			{
				if (_displayFilter == null)
				{
					_displayFilter = (new DisplayFilter()).GetDefault();
				}
			}
			if (cleanFilter == "true")
			{
				_displayFilter = (new DisplayFilter()).GetDefault();
			}

			if (displayFilter.AuthorFirstName == null && displayFilter.AuthorLastName == null && displayFilter.DepartureAddress == null && displayFilter.DestinationAddress == null)
			{
				_displayFilter = (new DisplayFilter()).GetDefault();
			}


			int pageSize = 5;
			int pageNumber = (page ?? 1);

			var model = new RequestIndexViewModel();
			var requestsList = _requestService.GetRequest(_displayFilter).OrderByDescending(x => x.Id);
			model.Requests = requestsList.ToPagedList(pageNumber, pageSize);

			return PartialView(model);
		}
		[Authorize(Roles = "Секретарь")]
		[HttpGet]
		public ActionResult SecretaryHandleRequest(int? id)
		{
			var error = "";
			if (id == null) return HttpNotFound();

			var model = new RequestHandleViewModel();

			var filter = new DisplayFilter();

			var ar = new DtoRequest();

			if (!_requestService.GetRequestById((int)id, out ar, out error)) return HttpNotFound();

			model.Request = ar;

			return View(model);
		}
		[Authorize(Roles = "Секретарь")]
		[HttpPost]
		public ActionResult SecretaryReject(RequestHandleViewModel model)
		{
			_requestService.UpdateRequestStatus(model.Request.Id, (int)Statuses.WasDeclined, model.Request.Comment);

			return RedirectToAction("Index", "Request");
		}

		[HttpPost]
		public ActionResult SecretaryFinishFailed(RequestHandleViewModel model)
		{
			_requestService.UpdateRequestStatus(model.Request.Id, (int)Statuses.WasCompletedPoorly, model.Request.Comment);

			return RedirectToAction("Index", "Request");
		}
		[Authorize(Roles = "Секретарь")]
		[HttpPost]
		public ActionResult SecretaryFinishSuccess(RequestHandleViewModel model)
		{
			_requestService.UpdateRequestStatus(model.Request.Id, (int)Statuses.WasCompletedSuccessfully, model.Request.Comment);

			return RedirectToAction("Index", "Request");
		}
		[Authorize(Roles = "Менеджер")]
		[HttpGet]
		public ActionResult PartialManagerIndex(DisplayFilter displayFilter, string cleanFilter, int? page)
		{

			if (displayFilter.AuthorFirstName != null || displayFilter.AuthorLastName != null || displayFilter.DepartureAddress != null || displayFilter.DestinationAddress != null)
			{
				Session["disFilter"] = displayFilter;
				_displayFilter = displayFilter;
			}
			else
			{
				if (_displayFilter == null && (DisplayFilter)Session["disFilter"] == null)
				{

Project/sources/ETOS/ETOS.WebUI/Views/Request/Create.cshtml
@model ETOS.WebUI.ViewModels.RequestsViewModels.CreateRequestModel
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Назад", "Index", "Request", new { @class = "btn btn-info back-btn" })
<h2>Новая заявка:</h2>
<br />
<div>
	@Html.AntiForgeryToken()
	@Html.ValidationSummary()

	@using (Html.BeginForm("Create", "Request", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
	{
		<h4>Когда:</h4>
		<div class="form-group">
			<label class="col-md-2 control-label"> Дата / Время:</label>
			<div class="col-md-4">
				@Html.TextBoxFor(m => m.Request.DepartureDateTime, new { @Value = DateTime.Now.ToString("dd.MM.yyyy hh:mm"), @class = "datepicker", @id = "datetimepicker1" })
			</div>
		</div>
		<br />
		<h4>Откуда:</h4>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Адрес из списка:
			</label>
			<div class="col-md-4">
				@Html.DropDownListFor(a => a.Request.DeparturePointId, Model.POIList as SelectList, "Выберите пункт отправления", new { @class = "form-control", @id = "fromCityList" })
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Произвольный адрес:
			</label>
			<div class="col-md-4">
				@Html.TextBoxFor(a => a.Request.DepartureAddress, new { @class = "form-control", @id = "fromCity" })
			</div>
		</div>
		<br />
		<h4>Куда:</h4>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Адрес из списка:
			</label>
			<div class="col-md-4">
				@Html.DropDownListFor(a => a.Request.DestinationPointId, Model.POIList, "Выберите пункт назначения", new { @class = "form-control", @id = "toCityList" })
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Произвольный адрес:
			</label>
			<div class="col-md-4">
				@Html.TextBoxFor(a => a.Request.DestinationAddress, new { @class = "form-control", @id = "toCity" })
			</div>
		</div>
		<br />
		<h4>Багаж:</h4>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Наличие:
			</label>
			<div class="col-md-4">
				@Html.CheckBox("request.HasBaggage", Model.Request.HasBaggage, new { @class = "customCheckbox" })
			</div>
		</div>
		<br />
		<h4>Комментарий к поездке:</h4>
		<div class="form-group">
			<label class="col-md-2 control-label">
				Текст:
			</label>
			<div class="col-md-4">
				@Html.TextAreaFor(m => m.Request.Comment, 3, 100, null)
			</div>
		</div>

			<h4>Примерное расстояние:</h4>
			<div class="form-group">
				<label class="col-md-2 control-label">
					КМ
				</label>
				<div class="col-md-4">
					@Html.TextBoxFor(m => m.Request.Mileage, new { @class = "form-control", @id = "distanceControl", @readonly = "true" })
				</div>
			</div>
			@Html.ListBox("request.POIListAddresses", @Model.POIListAddresses, new { @id = "poiAddressList", @Hidden = "true" })
			<div class="btn-group" role="group">
				<input type="submit" value="Отправить заявку" class="btn btn-success" id="sendRequestButton" disabled="true" />
			</div>
			<div>
			</div>
	}
</div>
<div>
	@if (Model.Errors != null)
	{
		foreach (var error in Model.Errors)
		{
			<div class="alert alert-danger">@error</div>
		}
	}
</div>
<br />
<div class="alert alert-danger" id="error_string" hidden="true"></div>
<br />
<div id="map" style="width: 600px; height: 400px" hidden="true"></div>


<script src="https://api-maps.yandex.ru/2.1/?lang=tr_TR"></script>
@Scripts.Render("~/bundles/geolocation")

Project/sources/ETOS/ETOS.WebUI/Views/Request/Edit.cshtml
@model ETOS.WebUI.ViewModels.RequestsViewModels.CreateRequestModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <title>Создание заявки</title>
</head>
<body>


    </ul>
    <br />
    <div>
        @using (Html.BeginForm())
        {
            //   @Html.AntiForgeryToken()
            // @Html.ValidationSummary()


            <table class="table">
                <tr>
                    <td align="right">
                        Дата время отправления:
                    </td>
                    <td align="left">
                        @Html.TextBoxFor(a => a.request.DepartureDateTime, new { @class = "form -control", style = "width: 200px;", type = "datetime", @Value = DateTime.Now })
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        Откуда:
                    </td>
                    <td align="left">
                        @Html.DropDownListFor(a => a.request.DeparturePointId, Model.POIList as SelectList, "Выберите пункт отправления", new { @class = "form -control", style = "width: 200px;" })
                    </td>
                    <td>
                        @Html.TextBoxFor(a => a.request.DepartureAddress, new { @class = "form-control", style = "width: 200px; text-align:center" })
                    </td>
                    <td>
                  @*      @Html.CheckBox("request.ManualDeparturePoint", Model.request.ManualDeparturePoint)*@
                        <label>Использовать введеный адрес</label>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        Куда:
                    </td>
                    <td align="left">
                        @Html.DropDownListFor(a => a.request.DestinationPointId, Model.POIList, "Выберите пункт назначения", new { @class = "form-control", style = "width: 200px;" })
                    </td>
                    <td>
                        @Html.TextBoxFor(a => a.request.DestinationAddress, new { @class = "form-control", style = "width: 200px; text-align:center" })
                    </td>
                    <td>
                   @*     @Html.CheckBox("request.ManualDestinationPoint", Model.request.ManualDestinationPoint)*@
                        <label>Использовать введеный адрес</label>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        Наличие багажа:
                    </td>
                    <td align="left">
                        @Html.CheckBox("request.HasBaggage", Model.request.HasBaggage)
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        Комментарий к поездке:
                    </td>
                    <td align="left">
                        @Html.TextBox("request.Comment", Model.request.Comment)
                    </td>
                </tr>
                <tr>
                <tr>
                    <td align="right"></td>
                    <td>
                        <input type="submit" value="Создать" class="form-control" style="width: 200px" />
                    </td>
                </tr>
            </table>
        }
    </div>


    <div>
        <table>
            @if (Model.errors != null)
            {
                foreach (var error in Model.errors)
                {

                    <tr>
                        <td>
                            @error
                        </td>
                    </tr>

                }
            }
        </table>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Project/sources/ETOS/ETOS.WebUI/Views/Request/Index.cshtml
@if (HttpContext.Current.User.IsInRole("Секретарь"))
{
    { Html.RenderPartial("PartialSecretaryIndex"); }
}

@if (HttpContext.Current.User.IsInRole("Пользователь"))
{
    { Html.RenderPartial("PartialRequestIndex"); }
}

@if (HttpContext.Current.User.IsInRole("Менеджер"))
{
    { Html.RenderPartial("PartialManagerIndex"); }
}

Project/sources/ETOS/ETOS.WebUI/Views/Request/SecretaryHandleRequest.cshtml
@model ETOS.WebUI.ViewModels.RequestsViewModels.RequestHandleViewModel
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
	<title>Секретарь</title>
</head>
<body>

	<br />
	<br />
	<h2>Описание заявки</h2>
	<br />

	<div>
		<table>
			<tr>
				<td>Время создания заявки</td>
				<td>@Model.Request.CreationDateTime</td>
			</tr>
			<tr>
				<td>ФИО</td>
				<td>@Model.Request.AuthorLastName  @Model.Request.AuthorFirstName</td>
			</tr>
			<tr>
				<td>Откуда</td>
				<td>@Model.Request.DeparturePointName</td>
			</tr>
			<tr>
				<td>Куда</td>
				<td>@Model.Request.DestinationPointName</td>
			</tr>
			<tr>
				<td>Время отправки</td>
				<td>@Model.Request.DepartureDateTime</td>
			</tr>
			<tr>
				<td>Багаж</td>
				<td>
					@if (Model.Request.HasBaggage)
					{
						<label>Есть</label>
					}
					else
					{
						<label>Отсутствует</label>
					}
				</td>
			</tr>
			<tr>
				<td>Комментарий</td>
				<td>@Model.Request.Comment</td>
			</tr>
			<tr>
				<td>Расстояние</td>
				<td>@Model.Request.Mileage</td>
			</tr>
			<tr>
				@if (Model.Request.Price > 0)
				{
					<td>
						Стоимость:
					</td>
					<td>
						@Model.Request.Price <label>руб</label>
					</td>
				}	
			</tr>
			<tr>
				<td>Статус</td>
				<td>@Model.Request.StatusName</td>
			</tr>
		</table>

		<h3>Действия</h3>
		<br />

		<div class="col-md-10">
			@using (Html.BeginForm("Select/" + @Model.Request.Id.ToString(), "Contractor", FormMethod.Get))
			{
				<input type="submit" value="Подобрать такси" class="btn btn-info" style="width: 200px" />
			}
		</div>
		<div class="col-md-10">
			@using (Html.BeginForm("SecretaryFinishFailed", "Request", FormMethod.Post))
			{
				@Html.HiddenFor(m => m.Request.Id, Model.Request.Id)
				@Html.HiddenFor(m => m.Request.StatusId, Model.Request.StatusId)
				<input type="submit" value="Завершена не успешно" class="btn btn-warning" style="width: 200px" />
			}
		</div>

		<div class="col-md-10">
			@using (Html.BeginForm("SecretaryFinishSuccess", "Request", FormMethod.Post))
			{
				@Html.HiddenFor(m => m.Request.Id, Model.Request.Id)
				@Html.HiddenFor(m => m.Request.StatusId, Model.Request.StatusId)
				<input type="submit" value="Завершена успешно" class="btn btn-success" style="width: 200px" />
			}
		</div>

		<table>
			<tr>
				@using (Html.BeginForm("SecretaryReject", "Request", FormMethod.Post))
			{
					<td>
						<div class="col-md-10">
							<input type="submit" value="Отклонить" class="btn btn-danger" style="width: 200px" />
						</div>
					</td>
					<td>
						<div class="col-md-10">
							<div>Причина</div>
							@Html.HiddenFor(m => m.Request.Id, Model.Request.Id)
							@Html.HiddenFor(m => m.Request.StatusId, Model.Request.StatusId)
						</div>
					</td>
					<td>
						<div class="col-md-10">
							@Html.TextBoxFor(a => a.Request.Comment, new { @class = "form-control", @Value="",style = "width: 360px; text-align:center" })
						</div>
					</td>
			}
			</tr>
		</table>
	</div>

	<script src="~/Scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>