Project/sources/ETOS/ETOS.WebUI/ViewModels/BrandViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ETOS.WebUI.ViewModels
{
	public class BrandListViewModel
	{
		public IEnumerable<BrandInfoViewModel> Brands { get; set; }
	}

	public class BrandInfoViewModel
	{
		/// <summary>
		/// Код марки автомобиля.
		/// </summary>
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		/// <summary>
		/// Название марки автомобиля.
		/// </summary>
		[Required(ErrorMessage = "Пожалуйста, укажите название марки автомобиля.")]
		[MaxLength(50, ErrorMessage = "Длина названия марки автомобиля не должна превышать 50 символов.")]
		[Display(Name = "Название марки")]
		public string Name { get; set; }

	}

	public class BrandDetailsViewModel
	{
		public BrandInfoViewModel Brand { get; set; }

		public IEnumerable<ModelInfoViewModel> BrandedModels { get; set; }
	}
}

Project/sources/ETOS/ETOS.WebUI/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ETOS.Core.DTO;
using ETOS.Core.Services;
using ETOS.Core.Services.Abstract;
using ETOS.WebUI.ViewModels;


namespace ETOS.WebUI.Controllers
{
	public class BrandController : Controller
	{
		#region Fields

		private readonly IBrandService _brandService;

		private readonly IModelService _modelService;

		#endregion

		#region Constructor

		public BrandController(IBrandService brandService, IModelService modelService)
		{
			_brandService = brandService;
			_modelService = modelService;
		}

		#endregion

		public ActionResult Index()
		{
			BrandListViewModel model = new BrandListViewModel
			{
				Brands = _brandService.GetBrandsList()
					.Select(br => new BrandInfoViewModel
					{
						Id = br.Id,
						Name = br.Name
					})
			};

			return View(model);
		}

		public ActionResult Create()
		{
			ViewBag.Title = "Добавление новой марки автомобиля";

			return View("Edit", new BrandInfoViewModel());
		}

		public ActionResult Edit(int brandId)
		{
			var brand = _brandService.GetBrand(brandId);
			var model = new BrandInfoViewModel { Id = brand.Id, Name = brand.Name };

			ViewBag.Title = "Редактирование марки автомобиля";

			return View(model);
		}

		public ActionResult Save(BrandInfoViewModel model)
		{
			var brandDto = new DtoBrand { Id = model.Id, Name = model.Name };

			_brandService.SaveBrand(brandDto);

			return RedirectToAction("Index");
		}

		public ActionResult Remove(int brandId)
		{
			if (brandId > 0)
			{
				_brandService.RemoveBrand(brandId);
			}
			else
			{
				return View("Error");
			}

			return RedirectToAction("Index");
		}

		public ActionResult Details (int brandId)
		{
			var brandDto = _brandService.GetBrand(brandId);
			var modelsDto = _modelService.GetBrandModelsList(brandId);

			var model = new BrandDetailsViewModel
			{
				Brand = new BrandInfoViewModel { Id = brandDto.Id, Name = brandDto.Name },
				BrandedModels = modelsDto
					.Select(m => new ModelInfoViewModel { Id = m.Id, Name = m.Name, BrandId = m.BrandId })
			};

			return View(model);
		}
	}
}

Project/sources/ETOS/ETOS.WebUI/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using ETOS.Core.DTO;
using ETOS.Core.Services;
using ETOS.Core.Services.Abstract;
using ETOS.WebUI.ViewModels;

namespace ETOS.WebUI.Controllers
{
	public class ModelController : Controller
	{
		#region Fields

		private readonly IModelService _modelService;

		#endregion

		#region Constructor

		public ModelController(IModelService modelService)
		{
			_modelService = modelService;
		}

		#endregion

		#region Methods

		public ActionResult Create(int brandId)
		{
			ViewBag.Title = "Добавление новой модели автомобиля";

			return View("Edit", new ModelInfoViewModel { BrandId = brandId });
		}

		public ActionResult Edit(int brandedModelId)
		{
			var brandedModel = _modelService.GetModel(brandedModelId);
			var model = new ModelInfoViewModel
			{
				Id = brandedModel.Id,
				Name = brandedModel.Name,
				BrandId = brandedModel.BrandId
			};

			ViewBag.Title = "Редактирование модели автомобиля";

			return View(model);
		}

		[HttpPost]
		public ActionResult Save(ModelInfoViewModel model)
		{
			var modelDto = new DtoModel { Id = model.Id, Name = model.Name, BrandId = model.BrandId };

			_modelService.SaveModel(modelDto);

			return RedirectToAction("Details", "Brand", new { @brandId = model.BrandId });
		}

		public ActionResult Remove(int brandId, int brandedModelId)
		{
			if (brandedModelId > 0)
			{
				_modelService.RemoveModel(brandedModelId);
			}
			else
			{
				return View("Error");
			}

			return RedirectToAction("Details", "Brand", new { @brandId = brandId });
		}

		#endregion
	}
}

Project/sources/ETOS/ETOS.WebUI/Views/Brand/Details.cshtml
@model BrandDetailsViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = $"Информация о марке автомобиля: { Model.Brand.Name }";
}
<div class="row">
    <div class="page-header">
        <h1>Информация о марке автомобиля: @Model.Brand.Name</h1>
    </div>
    <h2>Модельный ряд</h2>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Код модели</th>
                <th>Название модели</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.BrandedModels.Count() == 0)
            {
                <tr>
                    <td colspan="3" class="text-center">Модели отсутствуют</td>
                </tr>}
            else
            {
                foreach (var brandedModel in Model.BrandedModels)
                {
                    <tr>
                        <td>@brandedModel.Id</td>
                        <td>@brandedModel.Name</td>
                        <td hidden ="hidden">@brandedModel.BrandId</td>
                        <td>
                            @Html.ActionLink("Редактировать", "Edit", "Model", new { @brandedModelId = brandedModel.Id }, new { @class = "btn btn-primary btn-xs" })
                            @Html.ActionLink("Удалить", "Remove", "Model", new { @brandId = brandedModel.BrandId, brandedModelId = brandedModel.Id }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    @Html.ActionLink("Добавить модель автомобиля", "Create", "Model", new { @brandId = Model.Brand.Id }, new { @class = "btn btn-primary" })
</div>

Project/sources/ETOS/ETOS.WebUI/Views/Brand/Edit.cshtml
@model BrandInfoViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Save", "Brand", FormMethod.Post, new { @class = "form-horizontal" }))
{
    if (!ViewData.ModelState.IsValid)
    {
        <div class="form-group">
            @Html.ValidationSummary(false, "", new { @class = "col-md-4 col-md-offset-4 alert alert-danger" })
        </div>
    }
    <h1 class="page-header">@ViewBag.Title</h1>
    <div class="form-group row">
        @Html.HiddenFor(m => m.Id)
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-md " })
    </div>
    <div class="form-group media-right">
        <input type="submit" class="btn btn-success btn-sm" value="Сохранить" />
    </div>
}

Project/sources/ETOS/ETOS.WebUI/Views/Brand/Index.cshtml
@model BrandListViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Перечень марок автомобилей";
}
<div class="row">
    <div class="page-header">
        <h1>Перечень марок автомобилей</h1>
    </div>
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Код марки автомобиля</th>
                <th>Название марки автомобиля</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Brands.Count() == 0)
            {
                <tr>
                    <td colspan="3" class="text-center">Марки автомобилей отсутствуют</td>
                </tr>}
            else
            {
                foreach (var brand in Model.Brands)
                {
                    <tr>
                        <td>@brand.Id</td>
                        <td>@brand.Name</td>
                        <td>
                            @Html.ActionLink("Подробнее", "Details", new { @brandId = brand.Id }, new { @class = "btn btn-info btn-xs" })
                            @Html.ActionLink("Редактировать", "Edit", new { @brandId = brand.Id }, new { @class = "btn btn-primary btn-xs" })
                            @Html.ActionLink("Удалить", "Remove", new { @brandId = brand.Id }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
}
            }
        </tbody>
    </table>
    @Html.ActionLink("Добавить марку автомобиля", "Create", null, new { @class = "btn btn-primary" })
</div>